name: CI

on: [push, pull_request]

jobs:
  test:
    name: PHP ${{ matrix.php-versions }} Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        php-versions: ['5.6', '7.3']
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup PHP
      uses: shivammathur/setup-php@1.1.1
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: dom
    - run: composer install
    - name: Install Coveralls
      run: composer require cedx/coveralls
    - name: Install Infection
      run: wget https://github.com/infection/infection/releases/download/0.17.0/infection.phar && chmod +x infection.phar
      if: matrix.php-versions == '7.3'
    - name: PHPUnit Tests
      run: vendor/bin/phpunit
    - name: Run Infection
      run: ./infection.phar --min-msi=85 --threads=4
      env:
        INFECTION_BADGE_API_KEY: ${{ secrets.STRYKERAPIKEY }}
      if: matrix.php-versions == '7.3'
    - name: Report code coverage
      run: php bin/coveralls build/logs/clover.xml
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.coverallsToken }}
      if: matrix.php-versions == '7.3'
